### ISSUE TITLE
Possível problema nas intruções de comparação

### ISSUE THREAD

**Issue by yellak** [hevslc/JVM#133]
A função **getIndex()** retorna um valor sem sinal, mas o offset do branch é pra ser com sinal. Eu criei uma outra chamada **getBranchOffset()** no Utils. Acho que tem que trocar lá. Se eu estiver errado pode só fechar essa issue

![image](https://user-images.githubusercontent.com/38587447/98465410-9c45b080-21a7-11eb-9bc4-e9eaf810f127.png)

**Comment by hevslc** [comment]
Eu testei, e verifiquei se o valor do novo PC, ou ofsset fica correto.
Isso funciona sim. Mas valeu a observação!
@yellak
